### ISSUE TITLE
Integration should urlencode values

### ISSUE THREAD

**Issue by zalary** [activeprospect/leadconduit-integration-suppressionlist#14]

**Comment by zalary** [comment]
I should have written a better issue on this - sorry.  I think this came up with spaces and/or plus signs not being encoded correctly.  This might have even been related to https://github.com/activeprospect/leadconduit-client/issues/481 and not need anything at all.

Possibly what this integration needs is to have the expectation of what happens with certain characters defined and then more testing to make sure it behaves that way.

**Comment by chasingSublimity** [comment]
Looks like this issue was addressed [here](https://github.com/activeprospect/leadconduit-integration-suppressionlist/commit/a321a237fee0f3d9c44e6e6a406a75f90793d6b6) and [here](https://github.com/activeprospect/leadconduit-integration-suppressionlist/commit/02579f225198ffb81d0acdcce323477db9524a33).

Closing.
